# whitelist
branches:
  only:
    - master
rvm:  
  - 1.9.3  

before_script:  
  - "sudo bash spec/install_phantomjs.sh > /dev/null"  
  - sh -e /etc/init.d/xvfb start  

script:  
  - DISPLAY=:99.0 phantomjs spec/run_jasmine.js index.html?test_mode